services:
  postgres:
    image: postgres:15-alpine
    container_name: finguard_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-finguard}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend-node/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-finguard}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: finguard_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend-python:
    build: ./backend-python
    container_name: finguard-backend-python
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-finguard}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-finguard}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  backend-node:
    build: ./backend-node
    container_name: finguard-backend-node
    ports:
      - "3001:3001"
    environment:
      - PYTHON_API_URL=http://backend-python:8000
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-finguard}
      - REDIS_URL=redis://redis:6379
      - POSTGRES_DB=${POSTGRES_DB:-finguard}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_HOST=postgres
    depends_on:
      backend-python:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_NODE_API_URL: http://localhost:3001
    container_name: finguard-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_NODE_API_URL=http://localhost:3001
    depends_on:
      backend-node:
        condition: service_started


volumes:
  postgres_data:
